### ISSUE TITLE
read() doesn't pass the argument to read_average()

### ISSUE THREAD

**Issue by utdrmac** [fivesixzero/CircuitPython_HX711#3]
https://github.com/fivesixzero/CircuitPython_HX711/blob/main/hx711/__init__.py#L223

read() takes an arg, average_count. If > 1, call read_average() but does not pass the arg. read_average will always use 10 iterations no matter what number > 1 you give to read()

**Comment by fivesixzero** [comment]
🤦 

Good catch, embarassing mistake. 😂 

Thanks for posting the issue, I'll get an updated version pushed out with the fix.

_edit: Should be fixed via 4efc13f_
